### What are Tensors?
Tensors are multi-dimensional arrays with a uniform type (called a dtype ).\
They are immutable: you can never update the contents of a tensor, only create a new one.

### Creating Tensors in TensorFlow
Using the `constant` method

In [11]:
import tensorflow as tf

tensor_zero_d = tf.constant(4)

tensor_one_d = tf.constant([1,2,3])

tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [-1,-2,6]
])

tensor_three_d = tf.constant([
    [
        [1,2,3],
        [4,5,-6]
    ],

    [
        [1,2,3],
        [4,5,-6]
    ]
])

tensor_four_d = tf.constant(
    [
        [
            [
                [1,2,3],
                [4,5,-6]
            ],
        
            [
                [1,2,3],
                [4,5,-6]
            ]
        ],

        [
            [
                [1,2,3],
                [4,5,-6]
            ],
        
            [
                [1,2,3],
                [4,5,-6.]
            ]
        ]
    ]
)

print(f"zero dimentional tensor: ",tensor_zero_d)
print(f"\none dimentional tensor: ",tensor_one_d)
print(f"\ntwo dimentional tensor: ",tensor_two_d)
print(f"\nthree dimentional tensor: ",tensor_three_d)
print(f"\nfour dimentional tensor: ",tensor_four_d)


zero dimentional tensor:  tf.Tensor(4, shape=(), dtype=int32)

one dimentional tensor:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)

two dimentional tensor:  tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [-1 -2  6]], shape=(3, 3), dtype=int32)

three dimentional tensor:  tf.Tensor(
[[[ 1  2  3]
  [ 4  5 -6]]

 [[ 1  2  3]
  [ 4  5 -6]]], shape=(2, 2, 3), dtype=int32)

four dimentional tensor:  tf.Tensor(
[[[[ 1.  2.  3.]
   [ 4.  5. -6.]]

  [[ 1.  2.  3.]
   [ 4.  5. -6.]]]


 [[[ 1.  2.  3.]
   [ 4.  5. -6.]]

  [[ 1.  2.  3.]
   [ 4.  5. -6.]]]], shape=(2, 2, 2, 3), dtype=float32)


### Displaying the properties of tensor
. `dtype` -> Displays the type of data the tensor stores\
. `shape` -> Displays the shape of the tensor\
. `ndim`  -> Displays the dimension of the tensor

In [2]:
print("Data type stored by tensor_four_d : ",tensor_four_d.dtype)
print("Shape of tensor_two_d : ",tensor_two_d.shape)
print("Dimension of tensor_three_d : ",tensor_three_d.ndim)


Data type stored by tensor_four_d :  <dtype: 'float32'>
Shape of tensor_two_d :  (3, 3)
Dimension of tensor_three_d :  3


### Changing the type of the data stored by the tensors
Using `tf.cast`

In [3]:
print("Before Type Casting\n", tensor_four_d.dtype)
tensor_four_d = tf.cast(tensor_four_d,tf.int32)
print("\nAfter Type Casting\n", tensor_four_d.dtype)

Before Type Casting
 <dtype: 'float32'>

After Type Casting
 <dtype: 'int32'>


### Converting a Numpy array to tensor

In [4]:
import numpy as np

In [5]:
np_array = np.array([2,3,4])
print(np_array)

tensor_np_array = tf.convert_to_tensor(np_array, dtype=tf.float16)
print("\n",tensor_np_array)

[2 3 4]

 tf.Tensor([2. 3. 4.], shape=(3,), dtype=float16)


### Other useful Methods

`tf.eye` - Used to create a identity matrix tenor

In [6]:
tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[1],
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]], dtype=float32)>

`tf.fill` - Used to create a tensor by defining the dimension and what value to be filled.\
The tensor will contain only the provided value

In [7]:
tf.fill(
    dims=[2,3], value=1, name=None, layout=None
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

`tf.rank`- Returns the rank of a tensor.

The rank of a tensor is not the same as the rank of a matrix.\
The rank of a tensor is the number of indices required to uniquely select each element of\ the tensor. Rank is also known as "order", "degree", or "ndims."


In [8]:
tf.rank(
    input=tensor_four_d, name=None
)

#The rank is displayed in the numpy filed shown below
#The shape is not shown as the method returns a 0D tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

`tf.size` - Returns the size of the tensor

In [9]:
tf.size(tensor_four_d)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

### Generating Random valued tensors

##### Using `tf.random.normal`
Returns a tensor of the given shape that contains normal random values using the provided mean and standard deviation

In [24]:
tensor_random = tf.random.normal(
    shape = [2,3],
    mean = 2,
    stddev = 1,
    dtype = tf.float16
)
print(tensor_random)

tf.Tensor(
[[0.6455 2.705  2.037 ]
 [2.87   2.438  1.466 ]], shape=(2, 3), dtype=float16)


##### Using `tf.random.uniform`
Returns a tensor of the given shape that contains uniformly distributed random values using the provided min and max values

In [68]:
tensor_random = tf.random.uniform(
    shape = [5],
    minval= 0,
    maxval = 50,
    dtype = tf.int32
)
print(tensor_random)

tf.Tensor([30 13 26 10 46], shape=(5,), dtype=int32)


##### Using the `tf.random.set_seed`
Used to set the seed such that any random generator when provided with the same seed,\
produces the same set of random values

In [65]:
tf.random.set_seed(10)

for x in range (4):
    random_tensor = tf.random.uniform(shape=[5], minval=5, maxval=35, dtype=tf.int32, seed=10)
    print(random_tensor)

tf.Tensor([ 8 14 12 20  6], shape=(5,), dtype=int32)
tf.Tensor([ 8 12 27  9 32], shape=(5,), dtype=int32)
tf.Tensor([22 22 34  7 27], shape=(5,), dtype=int32)
tf.Tensor([25 34 19 17 21], shape=(5,), dtype=int32)


In [66]:
# Not Setting the Global seed will not generate the same set of random values as above
for x in range (4):
    random_tensor = tf.random.uniform(shape=[5], minval=5, maxval=35, dtype=tf.int32, seed=10)
    print(random_tensor)

tf.Tensor([24  5  7  8  7], shape=(5,), dtype=int32)
tf.Tensor([33 16 32 31 33], shape=(5,), dtype=int32)
tf.Tensor([27 14 15 20 13], shape=(5,), dtype=int32)
tf.Tensor([13  5  6 29 27], shape=(5,), dtype=int32)


In [67]:
# Setting the seed to the value same as above
tf.random.set_seed(10)
for x in range (4):
    random_tensor = tf.random.uniform(shape=[5], minval=5, maxval=35, dtype=tf.int32, seed=10)
    print(random_tensor)

tf.Tensor([ 8 14 12 20  6], shape=(5,), dtype=int32)
tf.Tensor([ 8 12 27  9 32], shape=(5,), dtype=int32)
tf.Tensor([22 22 34  7 27], shape=(5,), dtype=int32)
tf.Tensor([25 34 19 17 21], shape=(5,), dtype=int32)
