### What are Tensors?
Tensors are multi-dimensional arrays with a uniform type (called a dtype ).\
They are immutable: you can never update the contents of a tensor, only create a new one.

### Creating Tensors in TensorFlow
Using the `constant` method

In [15]:
import tensorflow as tf

tensor_zero_d = tf.constant(4)

tensor_one_d = tf.constant([1,2,3])

tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [-1,-2,6]
])

tensor_three_d = tf.constant([
    [
        [1,2,3],
        [4,5,-6]
    ],

    [
        [1,2,3],
        [4,5,-6]
    ]
])

tensor_four_d = tf.constant(
    [
        [
            [
                [1,2,3],
                [4,5,-6]
            ],
        
            [
                [1,2,3],
                [4,5,-6]
            ]
        ],

        [
            [
                [1,2,3],
                [4,5,-6]
            ],
        
            [
                [1,2,3],
                [4,5,-6.]
            ]
        ]
    ]
)

print(f"zero dimentional tensor: ",tensor_zero_d)
print(f"\none dimentional tensor: ",tensor_one_d)
print(f"\ntwo dimentional tensor: ",tensor_two_d)
print(f"\nthree dimentional tensor: ",tensor_three_d)
print(f"\nfour dimentional tensor: ",tensor_four_d)


zero dimentional tensor:  tf.Tensor(4, shape=(), dtype=int32)

one dimentional tensor:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)

two dimentional tensor:  tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [-1 -2  6]], shape=(3, 3), dtype=int32)

three dimentional tensor:  tf.Tensor(
[[[ 1  2  3]
  [ 4  5 -6]]

 [[ 1  2  3]
  [ 4  5 -6]]], shape=(2, 2, 3), dtype=int32)

four dimentional tensor:  tf.Tensor(
[[[[ 1.  2.  3.]
   [ 4.  5. -6.]]

  [[ 1.  2.  3.]
   [ 4.  5. -6.]]]


 [[[ 1.  2.  3.]
   [ 4.  5. -6.]]

  [[ 1.  2.  3.]
   [ 4.  5. -6.]]]], shape=(2, 2, 2, 3), dtype=float32)


### Displaying the properties of tensor
. `dtype` -> Displays the type of data the tensor stores\
. `shape` -> Displays the shape of the tensor\
. `ndim`  -> Displays the dimension of the tensor

In [16]:
print("Data type stored by tensor_four_d : ",tensor_four_d.dtype)
print("Shape of tensor_two_d : ",tensor_two_d.shape)
print("Dimension of tensor_three_d : ",tensor_three_d.ndim)


Data type stored by tensor_four_d :  <dtype: 'float32'>
Shape of tensor_two_d :  (3, 3)
Dimension of tensor_three_d :  3


### Changing the type of the data stored by the tensors
Using `tf.cast`

In [17]:
print("Before Type Casting\n", tensor_four_d.dtype)
tensor_four_d = tf.cast(tensor_four_d,tf.int32)
print("\nAfter Type Casting\n", tensor_four_d.dtype)

Before Type Casting
 <dtype: 'float32'>

After Type Casting
 <dtype: 'int32'>


### Converting a Numpy array to tensor

In [18]:
import numpy as np

In [19]:
np_array = np.array([2,3,4])
print(np_array)

tensor_np_array = tf.convert_to_tensor(np_array, dtype=tf.float16)
print("\n",tensor_np_array)

[2 3 4]

 tf.Tensor([2. 3. 4.], shape=(3,), dtype=float16)


### Other useful Methods

`tf.eye` - Used to create a identity matrix tenor

In [20]:
tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[1],
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]], dtype=float32)>

`tf.fill` - Used to create a tensor by defining the dimension and what value to be filled.\
The tensor will contain only the provided value

In [21]:
tf.fill(
    dims=[2,3], value=1, name=None, layout=None
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

`tf.rank`- Returns the rank of a tensor.

The rank of a tensor is not the same as the rank of a matrix.\
The rank of a tensor is the number of indices required to uniquely select each element of\ the tensor. Rank is also known as "order", "degree", or "ndims."


In [22]:
tf.rank(
    input=tensor_four_d, name=None
)

#The rank is displayed in the numpy filed shown below
#The shape is not shown as the method returns a 0D tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

`tf.size` - Returns the size of the tensor

In [23]:
tf.size(tensor_four_d)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

### Generating Random valued tensors

##### Using `tf.random.normal`
Returns a tensor of the given shape that contains normal random values using the provided mean and standard deviation

In [24]:
tensor_random = tf.random.normal(
    shape = [2,3],
    mean = 2,
    stddev = 1,
    dtype = tf.float16
)
print(tensor_random)

tf.Tensor(
[[1.124 2.336 1.647]
 [1.697 1.961 2.965]], shape=(2, 3), dtype=float16)


##### Using `tf.random.uniform`
Returns a tensor of the given shape that contains uniformly distributed random values using the provided min and max values

In [25]:
tensor_random = tf.random.uniform(
    shape = [5],
    minval= 0,
    maxval = 50,
    dtype = tf.int32
)
print(tensor_random)

tf.Tensor([43 45 19 21 14], shape=(5,), dtype=int32)


##### Using the `tf.random.set_seed`
Used to set the seed such that any random generator when provided with the same seed,\
produces the same set of random values

In [26]:
tf.random.set_seed(10)

for x in range (4):
    random_tensor = tf.random.uniform(shape=[5], minval=5, maxval=35, dtype=tf.int32, seed=10)
    print(random_tensor)

tf.Tensor([ 8 14 12 20  6], shape=(5,), dtype=int32)
tf.Tensor([ 8 12 27  9 32], shape=(5,), dtype=int32)
tf.Tensor([22 22 34  7 27], shape=(5,), dtype=int32)
tf.Tensor([25 34 19 17 21], shape=(5,), dtype=int32)


In [27]:
# Not Setting the Global seed will not generate the same set of random values as above
for x in range (4):
    random_tensor = tf.random.uniform(shape=[5], minval=5, maxval=35, dtype=tf.int32, seed=10)
    print(random_tensor)

tf.Tensor([24  5  7  8  7], shape=(5,), dtype=int32)
tf.Tensor([33 16 32 31 33], shape=(5,), dtype=int32)
tf.Tensor([27 14 15 20 13], shape=(5,), dtype=int32)
tf.Tensor([13  5  6 29 27], shape=(5,), dtype=int32)


In [28]:
# Setting the seed to the value same as above
tf.random.set_seed(10)
for x in range (4):
    random_tensor = tf.random.uniform(shape=[5], minval=5, maxval=35, dtype=tf.int32, seed=10)
    print(random_tensor)

tf.Tensor([ 8 14 12 20  6], shape=(5,), dtype=int32)
tf.Tensor([ 8 12 27  9 32], shape=(5,), dtype=int32)
tf.Tensor([22 22 34  7 27], shape=(5,), dtype=int32)
tf.Tensor([25 34 19 17 21], shape=(5,), dtype=int32)


### Indexing tensors

In [29]:
one_d_tensor = tf.constant([1,2,3,4,5,5,6],dtype=tf.int16)
print (one_d_tensor[0:-1])

tf.Tensor([1 2 3 4 5 5], shape=(6,), dtype=int16)


In [30]:
two_d_tensor = tf.constant([
    [1,2,3],
    [2,5,-8],
    [3,2,-8],
    [5,0,-4]
])

# Get the first three rows and first two columns
print(two_d_tensor[0:3,0:2])

# Get the second colum of every row
print(two_d_tensor[...,1])

tf.Tensor(
[[1 2]
 [2 5]
 [3 2]], shape=(3, 2), dtype=int32)
tf.Tensor([2 5 2 0], shape=(4,), dtype=int32)


### Maths

#### Absolute values  using the `tf.maths.abs`
#### For Real Numbers

In [32]:
tensor_var = tf.constant([1,2,-3])
print(tensor_var)

tf.Tensor([ 1  2 -3], shape=(3,), dtype=int32)


In [33]:
tensor_abs = tf.math.abs(tensor_var)
print(tensor_abs)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


#### For Complex numbers having the form a + bj


In [34]:
tensor_var = tf.constant([2+3j,5+4j])
print(tensor_var)

tf.Tensor([2.+3.j 5.+4.j], shape=(2,), dtype=complex128)


In [35]:
tensor_abs = tf.math.abs(tensor_var)
print(tensor_abs)

tf.Tensor([3.60555128 6.40312424], shape=(2,), dtype=float64)


#### Square Root

In [36]:
print(tf.math.sqrt(tensor_var))

tf.Tensor([1.67414923+0.89597748j 2.3877944 +0.83759305j], shape=(2,), dtype=complex128)


#### Basic arithmatic

In [38]:
tensor_one = tf.constant([1,2,3])
tensor_two = tf.constant(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print("ADD ", tf.math.add(tensor_one,tensor_two))
print("\nSUB ", tf.math.subtract(tensor_one,tensor_two))
print("\nMUL ", tf.math.multiply(tensor_one,tensor_two))
print("\nDIV ", tf.math.divide(tensor_one,tensor_two))

ADD  tf.Tensor(
[[2 4 6]
 [5 7 9]], shape=(2, 3), dtype=int32)

SUB  tf.Tensor(
[[ 0  0  0]
 [-3 -3 -3]], shape=(2, 3), dtype=int32)

MUL  tf.Tensor(
[[ 1  4  9]
 [ 4 10 18]], shape=(2, 3), dtype=int32)

DIV  tf.Tensor(
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]], shape=(2, 3), dtype=float64)


**NOTE**\
Though the dimension of the tensors dont match, arithmatic operation is being done by the concept of `stretching` the lower dimension vtensor to match the dimension of the higer dimension

#### power 
using `tf.math.pow`

In [39]:
tensor_three = tf.math.pow(tensor_one,tensor_two)
print(tensor_three)

tf.Tensor(
[[  1   4  27]
 [  1  32 729]], shape=(2, 3), dtype=int32)


#### Reduce sum
-> Returns the sum of all the elements present within the tensor

In [41]:
print(tf.math.reduce_sum(tensor_three))

tf.Tensor(794, shape=(), dtype=int32)
