### Some TensorFlow Functions

`tf.expand_dims()`\
Used to expand the dimension of the tensor

In [1]:
import tensorflow as tf

In [8]:
tensor_var = tf.constant([1,2,3])
print(tensor_var.shape)
tensor_var_expand = tf.expand_dims(tensor_var,axis=0)
print(tensor_var_expand.shape)

(3,)
(1, 3)


`tf.squeeze()`\
Used to squeeze the number of dimesions of the tensor

In [9]:
tensor_var_squeeze = tf.squeeze(tensor_var_expand)
print(tensor_var_squeeze)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


`tf.reshape()`\
Used to reshape the tensor by providing the order that must match the total number of elements in the tensor

In [10]:
# Here, the length of the tensor is 3, hence we need to provide the values that 
# when multiplied produces 3

tf.reshape(tensor_var,[3,1])

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [26]:
# here, we have tensor with lenth 4. So, these are the ways we can reshape them

tensor_var_2 = tf.constant([1,2,3,4])

print ("\n1 dimension\n",tf.reshape(tensor_var_2, [4]))
print ("\n2*2 grid\n",tf.reshape(tensor_var_2, [2,2]))
print ("\n1*4 grid\n",tf.reshape(tensor_var_2, [1,4]))
print ("\n4*1 grid\n",tf.reshape(tensor_var_2, [4,1]))


1 dimension
 tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)

2*2 grid
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)

1*4 grid
 tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)

4*1 grid
 tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)


`tf.concat`\
Used to concatinate tensors

In [37]:
t1 = tf.reshape(tensor_var_2,[2,2])
tf.concat([t1,t1],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]], dtype=int32)>

`tf.stack()`\
Used to stack a tensor over other

In [38]:
tf.stack([t1,t1],axis=0)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int32)>

`tf.pad()`\
Used for adding paddings around the tensor elements

In [50]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[2, 2,], [2, 2]])

tf.pad(tensor, paddings, "CONSTANT")

<tf.Tensor: shape=(6, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>